#!/usr/bin/env bash

hierarchy() {
  rm -f $HOME/.bashrc
  rm -f $HOME/.bash_profile
  rm -f $HOME/.bash_aliases
  rm -f $HOME/.profile

  mkdir -p $HOME/.config/vpn
  mkdir -p $HOME/.local/share/fonts
  mkdir -p $HOME/.local/share/icons
  mkdir -p $HOME/.local/share/themes
  mkdir -p $HOME/.local/share/applications
  mkdir -p $HOME/.mozilla/firefox/main.main/chrome

  sudo mkdir -p /usr/lib/firefox/distribution
}

main() {
  hierarchy
  cd source
  
  pushd house > /dev/null
  stow -v -t $HOME/ */
  popd > /dev/null
  
  pushd system/firefox > /dev/null
  sudo stow -v -t /usr/lib/firefox/distribution/ distribution/
  popd > /dev/null

  cd ..
}

main
