[[language]]
name = "c"
indent = { tab-width = 8, unit = "        " }
language-servers = [ "clangd" ]
file-types = [ "c", "h" ]
formatter = { command = "clang-format" }

[[language]]
name = "rust"
auto-format = false
